<?php
namespace ccxt;

// ----------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -----------------------------------------------------------------------------
include_once PATH_TO_CCXT . '/test/exchange/base/test_fetch_markets.php';

// eslint-disable-next-line no-undef
function kuru_test() {
    $exchange = new kuru();
    $markets = test_fetch_markets($exchange, array());
    return $markets;
}


kuru_test()->then(var_dump);
