# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.base.exchange import Exchange
from ccxt.abstract.kuru import ImplicitAPI
from ccxt.base.types import Int, Market, OrderBook
from typing import List
from ccxt.base.errors import InvalidOrder
from ccxt.base.errors import OrderNotFound
from ccxt.base.decimal_to_precision import DECIMAL_PLACES


class kuru(Exchange, ImplicitAPI):

    def describe(self):
        return self.deep_extend(super(kuru, self).describe(), {
            'id': 'kuru',
            'name': 'Kuru',
            'countries': [],
            'version': 'v1',
            'rateLimit': 50,  # 1200 requests per minute, 20 request per second
            'certified': False,
            'pro': True,
            'dex': True,
            'has': {
                'CORS': None,
                'spot': True,
                'margin': False,
                'swap': False,
                'future': False,
                'option': False,
                'addMargin': False,
                'borrowCrossMargin': False,
                'borrowIsolatedMargin': False,
                'cancelAllOrders': False,
                'cancelAllOrdersAfter': False,
                'cancelOrder': False,
                'cancelOrders': True,
                'cancelOrdersForSymbols': True,
                'closeAllPositions': False,
                'closePosition': False,
                'createMarketBuyOrderWithCost': False,
                'createMarketOrderWithCost': False,
                'createMarketSellOrderWithCost': False,
                'createOrder': False,
                'createOrders': False,
                'createReduceOnlyOrder': True,
                'editOrder': False,
                'fetchAccounts': False,
                'fetchBalance': False,
                'fetchBorrowInterest': False,
                'fetchBorrowRateHistories': False,
                'fetchBorrowRateHistory': False,
                'fetchCanceledAndClosedOrders': False,
                'fetchCanceledOrders': False,
                'fetchClosedOrders': False,
                'fetchCrossBorrowRate': False,
                'fetchCrossBorrowRates': False,
                'fetchCurrencies': False,
                'fetchDepositAddress': False,
                'fetchDepositAddresses': False,
                'fetchDeposits': False,
                'fetchDepositWithdrawFee': 'emulated',
                'fetchDepositWithdrawFees': False,
                'fetchFundingHistory': False,
                'fetchFundingRate': False,
                'fetchFundingRateHistory': False,
                'fetchFundingRates': False,
                'fetchIndexOHLCV': False,
                'fetchIsolatedBorrowRate': False,
                'fetchIsolatedBorrowRates': False,
                'fetchLedger': False,
                'fetchLeverage': False,
                'fetchLeverageTiers': False,
                'fetchLiquidations': False,
                'fetchMarginMode': None,
                'fetchMarketLeverageTiers': False,
                'fetchMarkets': True,
                'fetchMarkOHLCV': False,
                'fetchMyLiquidations': False,
                'fetchMyTrades': True,
                'fetchOHLCV': True,
                'fetchOpenInterest': False,
                'fetchOpenInterestHistory': False,
                'fetchOpenOrders': True,
                'fetchOrder': True,
                'fetchOrderBook': True,
                'fetchOrders': True,
                'fetchOrderTrades': False,
                'fetchPosition': True,
                'fetchPositionMode': False,
                'fetchPositions': True,
                'fetchPositionsRisk': False,
                'fetchPremiumIndexOHLCV': False,
                'fetchTicker': 'emulated',
                'fetchTickers': True,
                'fetchTime': False,
                'fetchTrades': True,
                'fetchTradingFee': True,
                'fetchTradingFees': False,
                'fetchTransfer': False,
                'fetchTransfers': False,
                'fetchWithdrawal': False,
                'fetchWithdrawals': True,
                'reduceMargin': True,
                'repayCrossMargin': False,
                'repayIsolatedMargin': False,
                'sandbox': True,
                'setLeverage': True,
                'setMarginMode': True,
                'setPositionMode': False,
                'transfer': True,
                'withdraw': True,
            },
            'timeframes': {
                '1s': '1s',
                '1m': '1m',
                '5m': '5m',
                '15m': '15m',
                '1h': '1h',
                '1d': '1d',
            },
            'hostname': 'kuru.io',
            'urls': {
                'logo': 'https://github.com/ccxt/ccxt/assets/43336371/b371bc6c-4a8c-489f-87f4-20a913dd8d4b',
                'api': {
                    # 'public': 'https://api.{hostname}',
                    # 'private': 'https://api.{hostname}',
                    'public': 'http:://127.0.0.1:9090/',
                    'private': 'http://127.0.0.1:9090/',
                },
                'test': {
                    'public': 'http:://127.0.0.1:9090/',
                    'private': 'http://127.0.0.1:9090/',
                },
                'www': 'https://kuru.io',
                'doc': 'https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api',
                'fees': 'https://hyperliquid.gitbook.io/hyperliquid-docs/trading/fees',
                'referral': 'https://app.hyperliquid.xyz/',
            },
            'api': {
                'public': {
                    'get': {
                        '/': 1,
                        'fetchMarkets': 1,
                        'fetchOrders': 1,
                        'fetchOrderbook': 1,
                        'fetchOrder': 1,
                        'fetchTrades': 1,
                        'fetchOHLCV': 1,
                    },
                },
                'private': {
                    'get': {
                        'fetchOpenOrders': 1,
                        'fetchClosedOrders': 1,
                        'fetchStatus': 1,
                        'fetchMyTrades': 1,
                    },
                    'post': {
                        'createOrder': 1,
                        'cancelOrder': 1,
                    },
                },
            },
            'fees': {
                'swap': {
                    'taker': self.parse_number('0.00035'),
                    'maker': self.parse_number('0.0001'),
                },
                'spot': {
                    'taker': self.parse_number('0.00035'),
                    'maker': self.parse_number('0.0001'),
                },
            },
            'requiredCredentials': {
                'apiKey': False,
                'secret': False,
                'walletAddress': True,
                'privateKey': True,
            },
            'exceptions': {
                'exact': {},
                'broad': {
                    'Price must be divisible by tick size.': InvalidOrder,
                    'Order must have minimum value of $10': InvalidOrder,
                    'Insufficient margin to place order.': InvalidOrder,
                    'Reduce only order would increase position.': InvalidOrder,
                    'Post only order would have immediately matched,': InvalidOrder,
                    'Order could not immediately match against any resting orders.':
            InvalidOrder,
                    'Invalid TP/SL price.': InvalidOrder,
                    'No liquidity available for market order.': InvalidOrder,
                    'Order was never placed, already canceled, or filled.': OrderNotFound,
                    'User or API Wallet ': InvalidOrder,
                    'Order has invalid size': InvalidOrder,
                    'Order price cannot be more than 80% away from the reference price':
            InvalidOrder,
                },
            },
            'precisionMode': DECIMAL_PLACES,
            'commonCurrencies': {},
            'options': {
                'defaultType': 'swap',
                'sandboxMode': False,
                'defaultSlippage': 0.05,
                # TODO: Change self to testnet/mainnet address
                'kuruForwarder': '0x0165878A594ca255338adfa4d48449f69242Eb8F',
                'chainId': '31337',
            },
        })

    def set_sandbox_mode(self, enabled):
        super(kuru, self).set_sandbox_mode(enabled)
        self.options['sandboxMode'] = enabled

    def fetch_markets(self, params={}) -> List[Market]:
        print('fetchMarkets')
        print('api', self.publicGetFetchMarkets)
        response = self.publicGetFetchMarkets(params)
        markets = response.data
        return markets

    def parse_market(self, apiResponse: dict) -> Market:
        market: Market = {
            'id': self.safe_string(apiResponse, 'market_address'),
            'symbol': self.safe_string(apiResponse, 'symbol'),
            'base': self.safe_string(apiResponse, 'base'),
            'quote': self.safe_string(apiResponse, 'quote'),
            'baseId': self.safe_string(apiResponse, 'baseId'),
            'quoteId': self.safe_string(apiResponse, 'quoteId'),
            'settleId': None,
            'type': 'spot',
            'subType': None,
            'spot': True,
            'margin': False,
            'swap': False,
            'future': False,
            'option': False,
            'contract': False,
            'linear': False,
            'inverse': False,
            'quanto': False,
            'settle': None,
            'contractSize': None,
            'expiry': None,
            'expiryDatetime': None,
            'optionType': None,
            'active': True,
            'taker': self.safe_number(apiResponse, 'taker_fee_bps'),
            'maker': self.safe_number(apiResponse, 'maker_fee_bps'),
            'percentage': False,
            'tierBased': False,
            'feeSide': None,
            'precision': {
                'price': self.safe_integer(apiResponse['precision'], 'price'),
                'amount': self.safe_integer(apiResponse['precision'], 'size'),
                'cost': None,
            },
            'limits': {
                'leverage': {
                    'min': None,
                    'max': None,
                },
                'amount': {
                    'min': None,
                    'max': None,
                },
                'price': {
                    'min': None,
                    'max': None,
                },
                'cost': {
                    'min': None,
                    'max': None,
                },
            },
            'created': apiResponse['created'],
            'info': None,
            'strike': None,
        }
        return market

    def fetch_order_book(self, symbol: str, limit: Int = None, params={}) -> OrderBook:
        marketAddress = params['marketAddress']
        if not marketAddress:
            raise Error('marketAddress is required')
        request: dict = {
            'marketAddress': marketAddress,
            'limit': limit,
        }
        response = self.publicGetFetchOrderbook(request)
        return self.parse_order_book(response)

    def parse_order_book(self, apiResponse: dict) -> OrderBook:
        orderbook: OrderBook = {
            'asks': apiResponse['asks'],
            'bids': apiResponse['bids'],
            'datetime': apiResponse['datetime'],
            'timestamp': apiResponse['timestamp'],
            'symbol': apiResponse['symbol'],
            'nonce': None,
        }
        return orderbook

    def fetch_ohlcv(self, symbol: str, timeframe='1m', since: Int = None, limit: Int = None, params={}) -> List[list]:
        marketAddressOHLCV = params['marketAddress']
        if not marketAddressOHLCV:
            raise Error('marketAddress is required')
        request: dict = {
            'marketAddress': marketAddressOHLCV,
            'timeframe': timeframe,
            'since': since,
        }
        response = self.publicGetFetchOHLCV(request)
        return self.parse_ohlcv_data(response)

    def parse_ohlcv_data(self, apiResponse: List[dict]) -> List[list]:
        ohlcv: List[OHLCV] = apiResponse.map((ohlcvData) => [ohlcvData['start_time'],
            ohlcvData['open'],
            ohlcvData['high'],
            ohlcvData['low'],
            ohlcvData['close'],
            ohlcvData['volume']])
        return ohlcv

    def hash_message(self, message):
        return '0x' + self.hash(message, 'keccak', 'hex')

    def sign_hash(self, hash, privateKey):
        signature = self.ecdsa(hash[-64:], privateKey[-64:], 'secp256k1', None)
        return {
            'r': '0x' + signature['r'],
            's': '0x' + signature['s'],
            'v': self.sum(27, signature['v']),
        }

    def sign_message(self, message, privateKey):
        return self.sign_hash(self.hash_message(message), privateKey[-64:])

    def sign_user_signed_action(self, messageTypes, message):
        verifyingContract = self.safe_string(self.options, 'kuruForwarder')
        chainId = self.safe_number(self.options, 'chainId')
        domain: dict = {
            'chainId': chainId,
            'name': 'KuruForwarder',
            'verifyingContract': verifyingContract,
            'version': '1.0.0',
        }
        msg = self.eth_encode_structured_data(domain, messageTypes, message)
        signature = self.sign_message(msg, self.privateKey)
        return signature

    def construct_phantom_agent(self, hash, isTestnet=True):
    #     source = 'b' if (isTestnet) else 'a'
    #     return {
    #         'source': source,
    #         'connectionId': hash,
    #     }
        pass

    def action_hash(self, action, vaultAddress, nonce):
    #     dataBinary = self.packb(action)
    #     dataHex = self.binary_to_base16(dataBinary)
    #     data = dataHex
    #     data += '00000' + self.int_to_base16(nonce)
    #     if vaultAddress is None:
    #         data += '00'
    #     else:
    #         data += '01'
    #         data += vaultAddress
    #     }
    #     return self.hash(self.base16_to_binary(data), 'keccak', 'binary')
        pass

    def sign_l1_action(self, action, nonce, vaultAdress=None) -> object:
    #     hash = self.action_hash(action, vaultAdress, nonce)
    #     isTestnet = self.safe_bool(self.options, 'sandboxMode', False)
    #     phantomAgent = self.construct_phantom_agent(hash, isTestnet)
    #     # data: Dict = {
    #     #     'domain': {
    #     #         'chainId': 1337,
    #     #         'name': 'Exchange',
    #     #         'verifyingContract': '0x0000000000000000000000000000000000000000',
    #     #         'version': '1',
    #     #     },
    #     #     'types': {
    #     #         'Agent': [
    #     #             {'name': 'source', 'type': 'string'},
    #     #             {'name': 'connectionId', 'type': 'bytes32'},
    #     #         ],
    #     #         'EIP712Domain': [
    #     #             {'name': 'name', 'type': 'string'},
    #     #             {'name': 'version', 'type': 'string'},
    #     #             {'name': 'chainId', 'type': 'uint256'},
    #     #             {'name': 'verifyingContract', 'type': 'address'},
    #     #         ],
    #     #     },
    #     #     'primaryType': 'Agent',
    #     #     'message': phantomAgent,
    #     # }
    #     zeroAddress = self.safe_string(self.options, 'zeroAddress')
    #     chainId = 1337  # check self out
    #     domain: Dict = {
    #         'chainId': chainId,
    #         'name': 'Exchange',
    #         'verifyingContract': zeroAddress,
    #         'version': '1',
    #     }
    #     messageTypes: Dict = {
    #         'Agent': [
    #             {'name': 'source', 'type': 'string'},
    #             {'name': 'connectionId', 'type': 'bytes32'},
    #         ],
    #     }
    #     msg = self.eth_encode_structured_data(domain, messageTypes, phantomAgent)
    #     signature = self.sign_message(msg, self.privateKey)
    #     return signature
        pass

    def sign_user_signed_action(self, messageTypes, message):
    #     zeroAddress = self.safe_string(self.options, 'zeroAddress')
    #     chainId = 421614  # check self out
    #     domain: Dict = {
    #         'chainId': chainId,
    #         'name': 'HyperliquidSignTransaction',
    #         'verifyingContract': zeroAddress,
    #         'version': '1',
    #     }
    #     msg = self.eth_encode_structured_data(domain, messageTypes, message)
    #     signature = self.sign_message(msg, self.privateKey)
    #     return signature
        pass
