// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class kuru : Exchange
{
    public kuru (object args = null): base(args) {}

    public async Task<object> publicGet (object parameters = null)
    {
        return await this.callAsync ("publicGet",parameters);
    }

    public async Task<object> publicGetFetchMarkets (object parameters = null)
    {
        return await this.callAsync ("publicGetFetchMarkets",parameters);
    }

    public async Task<object> publicGetFetchOrders (object parameters = null)
    {
        return await this.callAsync ("publicGetFetchOrders",parameters);
    }

    public async Task<object> publicGetFetchOrderbook (object parameters = null)
    {
        return await this.callAsync ("publicGetFetchOrderbook",parameters);
    }

    public async Task<object> publicGetFetchOrder (object parameters = null)
    {
        return await this.callAsync ("publicGetFetchOrder",parameters);
    }

    public async Task<object> publicGetFetchTrades (object parameters = null)
    {
        return await this.callAsync ("publicGetFetchTrades",parameters);
    }

    public async Task<object> publicGetFetchOHLCV (object parameters = null)
    {
        return await this.callAsync ("publicGetFetchOHLCV",parameters);
    }

    public async Task<object> privateGetFetchOpenOrders (object parameters = null)
    {
        return await this.callAsync ("privateGetFetchOpenOrders",parameters);
    }

    public async Task<object> privateGetFetchClosedOrders (object parameters = null)
    {
        return await this.callAsync ("privateGetFetchClosedOrders",parameters);
    }

    public async Task<object> privateGetFetchStatus (object parameters = null)
    {
        return await this.callAsync ("privateGetFetchStatus",parameters);
    }

    public async Task<object> privateGetFetchMyTrades (object parameters = null)
    {
        return await this.callAsync ("privateGetFetchMyTrades",parameters);
    }

    public async Task<object> privatePostCreateOrder (object parameters = null)
    {
        return await this.callAsync ("privatePostCreateOrder",parameters);
    }

    public async Task<object> privatePostCancelOrder (object parameters = null)
    {
        return await this.callAsync ("privatePostCancelOrder",parameters);
    }

}