// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

import { implicitReturnType } from '../base/types.js';
import { Exchange as _Exchange } from '../base/Exchange.js';

interface Exchange {
    publicGetFetchMarkets (params?: {}): Promise<implicitReturnType>;
    publicGetFetchOrders (params?: {}): Promise<implicitReturnType>;
    publicGetFetchOrderbook (params?: {}): Promise<implicitReturnType>;
    publicGetFetchOrder (params?: {}): Promise<implicitReturnType>;
    publicGetFetchTrades (params?: {}): Promise<implicitReturnType>;
    publicGetFetchOHLCV (params?: {}): Promise<implicitReturnType>;
    privateGetFetchOpenOrders (params?: {}): Promise<implicitReturnType>;
    privateGetFetchClosedOrders (params?: {}): Promise<implicitReturnType>;
    privateGetFetchStatus (params?: {}): Promise<implicitReturnType>;
    privateGetFetchMyTrades (params?: {}): Promise<implicitReturnType>;
    privatePostCreateOrder (params?: {}): Promise<implicitReturnType>;
    privatePostCancelOrder (params?: {}): Promise<implicitReturnType>;
}
abstract class Exchange extends _Exchange {}

export default Exchange
