<?php

namespace ccxt\async;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use ccxt\async\abstract\kuru as Exchange;
use React\Async;
use React\Promise\PromiseInterface;

class kuru extends Exchange {

    public function describe() {
        return $this->deep_extend(parent::describe(), array(
            'id' => 'kuru',
            'name' => 'Kuru',
            'countries' => array(),
            'version' => 'v1',
            'rateLimit' => 50, // 1200 requests per minute, 20 request per second
            'certified' => false,
            'pro' => true,
            'dex' => true,
            'has' => array(
                'CORS' => null,
                'spot' => true,
                'margin' => false,
                'swap' => false,
                'future' => false,
                'option' => false,
                'addMargin' => false,
                'borrowCrossMargin' => false,
                'borrowIsolatedMargin' => false,
                'cancelAllOrders' => false,
                'cancelAllOrdersAfter' => false,
                'cancelOrder' => false,
                'cancelOrders' => true,
                'cancelOrdersForSymbols' => true,
                'closeAllPositions' => false,
                'closePosition' => false,
                'createMarketBuyOrderWithCost' => false,
                'createMarketOrderWithCost' => false,
                'createMarketSellOrderWithCost' => false,
                'createOrder' => false,
                'createOrders' => false,
                'createReduceOnlyOrder' => true,
                'editOrder' => false,
                'fetchAccounts' => false,
                'fetchBalance' => false,
                'fetchBorrowInterest' => false,
                'fetchBorrowRateHistories' => false,
                'fetchBorrowRateHistory' => false,
                'fetchCanceledAndClosedOrders' => false,
                'fetchCanceledOrders' => false,
                'fetchClosedOrders' => false,
                'fetchCrossBorrowRate' => false,
                'fetchCrossBorrowRates' => false,
                'fetchCurrencies' => false,
                'fetchDepositAddress' => false,
                'fetchDepositAddresses' => false,
                'fetchDeposits' => false,
                'fetchDepositWithdrawFee' => 'emulated',
                'fetchDepositWithdrawFees' => false,
                'fetchFundingHistory' => false,
                'fetchFundingRate' => false,
                'fetchFundingRateHistory' => false,
                'fetchFundingRates' => false,
                'fetchIndexOHLCV' => false,
                'fetchIsolatedBorrowRate' => false,
                'fetchIsolatedBorrowRates' => false,
                'fetchLedger' => false,
                'fetchLeverage' => false,
                'fetchLeverageTiers' => false,
                'fetchLiquidations' => false,
                'fetchMarginMode' => null,
                'fetchMarketLeverageTiers' => false,
                'fetchMarkets' => true,
                'fetchMarkOHLCV' => false,
                'fetchMyLiquidations' => false,
                'fetchMyTrades' => true,
                'fetchOHLCV' => true,
                'fetchOpenInterest' => false,
                'fetchOpenInterestHistory' => false,
                'fetchOpenOrders' => true,
                'fetchOrder' => true,
                'fetchOrderBook' => true,
                'fetchOrders' => true,
                'fetchOrderTrades' => false,
                'fetchPosition' => true,
                'fetchPositionMode' => false,
                'fetchPositions' => true,
                'fetchPositionsRisk' => false,
                'fetchPremiumIndexOHLCV' => false,
                'fetchTicker' => 'emulated',
                'fetchTickers' => true,
                'fetchTime' => false,
                'fetchTrades' => true,
                'fetchTradingFee' => true,
                'fetchTradingFees' => false,
                'fetchTransfer' => false,
                'fetchTransfers' => false,
                'fetchWithdrawal' => false,
                'fetchWithdrawals' => true,
                'reduceMargin' => true,
                'repayCrossMargin' => false,
                'repayIsolatedMargin' => false,
                'sandbox' => true,
                'setLeverage' => true,
                'setMarginMode' => true,
                'setPositionMode' => false,
                'transfer' => true,
                'withdraw' => true,
            ),
            'timeframes' => array(
                '1s' => '1s',
                '1m' => '1m',
                '5m' => '5m',
                '15m' => '15m',
                '1h' => '1h',
                '1d' => '1d',
            ),
            'hostname' => 'kuru.io',
            'urls' => array(
                'logo' => 'https://github.com/ccxt/ccxt/assets/43336371/b371bc6c-4a8c-489f-87f4-20a913dd8d4b',
                'api' => array(
                    // 'public' => 'https://api.{hostname}',
                    // 'private' => 'https://api.{hostname}',
                    'public' => 'http:://127.0.0.1:9090/',
                    'private' => 'http://127.0.0.1:9090/',
                ),
                'test' => array(
                    'public' => 'http:://127.0.0.1:9090/',
                    'private' => 'http://127.0.0.1:9090/',
                ),
                'www' => 'https://kuru.io',
                'doc' => 'https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api',
                'fees' => 'https://hyperliquid.gitbook.io/hyperliquid-docs/trading/fees',
                'referral' => 'https://app.hyperliquid.xyz/',
            ),
            'api' => array(
                'public' => array(
                    'get' => array(
                        '/' => 1,
                        'fetchMarkets' => 1,
                        'fetchOrders' => 1,
                        'fetchOrderbook' => 1,
                        'fetchOrder' => 1,
                        'fetchTrades' => 1,
                        'fetchOHLCV' => 1,
                    ),
                ),
                'private' => array(
                    'get' => array(
                        'fetchOpenOrders' => 1,
                        'fetchClosedOrders' => 1,
                        'fetchStatus' => 1,
                        'fetchMyTrades' => 1,
                    ),
                    'post' => array(
                        'createOrder' => 1,
                        'cancelOrder' => 1,
                    ),
                ),
            ),
            'fees' => array(
                'swap' => array(
                    'taker' => $this->parse_number('0.00035'),
                    'maker' => $this->parse_number('0.0001'),
                ),
                'spot' => array(
                    'taker' => $this->parse_number('0.00035'),
                    'maker' => $this->parse_number('0.0001'),
                ),
            ),
            'requiredCredentials' => array(
                'apiKey' => false,
                'secret' => false,
                'walletAddress' => true,
                'privateKey' => true,
            ),
            'exceptions' => array(
                'exact' => array(),
                'broad' => array(
                    'Price must be divisible by tick size.' => '\\ccxt\\InvalidOrder',
                    'Order must have minimum value of $10' => '\\ccxt\\InvalidOrder',
                    'Insufficient margin to place order.' => '\\ccxt\\InvalidOrder',
                    'Reduce only order would increase position.' => '\\ccxt\\InvalidOrder',
                    'Post only order would have immediately matched,' => '\\ccxt\\InvalidOrder',
                    'Order could not immediately match against any resting orders.':
            '\\ccxt\\InvalidOrder',
                    'Invalid TP/SL price.' => '\\ccxt\\InvalidOrder',
                    'No liquidity available for market order.' => '\\ccxt\\InvalidOrder',
                    'Order was never placed, already canceled, or filled.' => '\\ccxt\\OrderNotFound',
                    'User or API Wallet ' => '\\ccxt\\InvalidOrder',
                    'Order has invalid size' => '\\ccxt\\InvalidOrder',
                    'Order price cannot be more than 80% away from the reference price':
            '\\ccxt\\InvalidOrder',
                ),
            ),
            'precisionMode' => DECIMAL_PLACES,
            'commonCurrencies' => array(),
            'options' => array(
                'defaultType' => 'swap',
                'sandboxMode' => false,
                'defaultSlippage' => 0.05,
                // TODO => Change this to testnet/mainnet address
                'kuruForwarder' => '0x0165878A594ca255338adfa4d48449f69242Eb8F',
                'chainId' => '31337',
            ),
        ));
    }

    public function set_sandbox_mode($enabled) {
        parent::set_sandbox_mode($enabled);
        $this->options['sandboxMode'] = $enabled;
    }

    public function fetch_markets($params = array ()): PromiseInterface {
        return Async\async(function () use ($params) {
            var_dump ('fetchMarkets');
            var_dump ('api', $this->publicGetFetchMarkets);
            $response = Async\await($this->publicGetFetchMarkets ($params));
            $markets = $response->data;
            return $markets;
        }) ();
    }

    public function parse_market(array $apiResponse): array {
        $market = array(
            'id' => $this->safe_string($apiResponse, 'market_address'),
            'symbol' => $this->safe_string($apiResponse, 'symbol'),
            'base' => $this->safe_string($apiResponse, 'base'),
            'quote' => $this->safe_string($apiResponse, 'quote'),
            'baseId' => $this->safe_string($apiResponse, 'baseId'),
            'quoteId' => $this->safe_string($apiResponse, 'quoteId'),
            'settleId' => null,
            'type' => 'spot',
            'subType' => null,
            'spot' => true,
            'margin' => false,
            'swap' => false,
            'future' => false,
            'option' => false,
            'contract' => false,
            'linear' => false,
            'inverse' => false,
            'quanto' => false,
            'settle' => null,
            'contractSize' => null,
            'expiry' => null,
            'expiryDatetime' => null,
            'optionType' => null,
            'active' => true,
            'taker' => $this->safe_number($apiResponse, 'taker_fee_bps'),
            'maker' => $this->safe_number($apiResponse, 'maker_fee_bps'),
            'percentage' => false,
            'tierBased' => false,
            'feeSide' => null,
            'precision' => array(
                'price' => $this->safe_integer($apiResponse['precision'], 'price'),
                'amount' => $this->safe_integer($apiResponse['precision'], 'size'),
                'cost' => null,
            ),
            'limits' => array(
                'leverage' => array(
                    'min' => null,
                    'max' => null,
                ),
                'amount' => array(
                    'min' => null,
                    'max' => null,
                ),
                'price' => array(
                    'min' => null,
                    'max' => null,
                ),
                'cost' => array(
                    'min' => null,
                    'max' => null,
                ),
            ),
            'created' => $apiResponse['created'],
            'info' => null,
            'strike' => null,
        );
        return $market;
    }

    public function fetch_order_book(string $symbol, ?int $limit = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $limit, $params) {
            $marketAddress = $params['marketAddress'];
            if (!$marketAddress) {
                throw new \Exception('marketAddress is required');
            }
            $request = array(
                'marketAddress' => $marketAddress,
                'limit' => $limit,
            );
            $response = Async\await($this->publicGetFetchOrderbook ($request));
            return $this->parse_order_book($response);
        }) ();
    }

    public function parse_order_book(array $apiResponse): array {
        $orderbook => OrderBook = array(
            'asks' => $apiResponse['asks'],
            'bids' => $apiResponse['bids'],
            'datetime' => $apiResponse['datetime'],
            'timestamp' => $apiResponse['timestamp'],
            'symbol' => $apiResponse['symbol'],
            'nonce' => null,
        );
        return $orderbook;
    }

    public function fetch_ohlcv(string $symbol, $timeframe = '1m', ?int $since = null, ?int $limit = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $timeframe, $since, $limit, $params) {
            $marketAddressOHLCV = $params['marketAddress'];
            if (!$marketAddressOHLCV) {
                throw new \Exception('marketAddress is required');
            }
            $request = array(
                'marketAddress' => $marketAddressOHLCV,
                'timeframe' => $timeframe,
                'since' => $since,
            );
            $response = Async\await($this->publicGetFetchOHLCV ($request));
            return $this->parse_ohlcv_data($response);
        }) ();
    }

    public function parse_ohlcv_data(array $apiResponse): array {
        $ohlcv => OHLCVarray() = $apiResponse->map ((ohlcvData) => [ ohlcvData['start_time'],
            ohlcvData['open'],
            ohlcvData['high'],
            ohlcvData['low'],
            ohlcvData['close'],
            ohlcvData['volume'] ]);
        return $ohlcv;
    }

    public function hash_message($message) {
        return '0x' . $this->hash($message, 'keccak', 'hex');
    }

    public function sign_hash($hash, $privateKey) {
        $signature = $this->ecdsa(mb_substr($hash, -64), mb_substr($privateKey, -64), 'secp256k1', null);
        return array(
            'r' => '0x' . $signature['r'],
            's' => '0x' . $signature['s'],
            'v' => $this->sum(27, $signature['v']),
        );
    }

    public function sign_message($message, $privateKey) {
        return $this->sign_hash($this->hash_message($message), mb_substr($privateKey, -64));
    }

    public function sign_user_signed_action($messageTypes, $message) {
        $verifyingContract = $this->safe_string($this->options, 'kuruForwarder');
        $chainId = $this->safe_number($this->options, 'chainId');
        $domain = array(
            'chainId' => $chainId,
            'name' => 'KuruForwarder',
            'verifyingContract' => $verifyingContract,
            'version' => '1.0.0',
        );
        $msg = $this->eth_encode_structured_data($domain, $messageTypes, $message);
        $signature = $this->sign_message($msg, $this->privateKey);
        return $signature;
    }

    public function construct_phantom_agent($hash, $isTestnet = true) {
    //     $source = ($isTestnet) ? 'b' : 'a';
    //     return array(
    //         'source' => $source,
    //         'connectionId' => $hash,
    //     );
    }

    public function action_hash($action, $vaultAddress, $nonce) {
    //     $dataBinary = $this->packb($action);
    //     $dataHex = bin2hex($dataBinary);
    //     $data = $dataHex;
    //     $data .= '00000' . $this->int_to_base16($nonce);
    //     if ($vaultAddress === null) {
    //         $data .= '00';
    //     } else {
    //         $data .= '01';
    //         $data .= $vaultAddress;
    //     }
    //     return $this->hash($this->base16_to_binary($data), 'keccak', 'binary');
    }

    public function sign_l1_action($action, $nonce, $vaultAdress = null): array {
    //     $hash = $this->action_hash($action, $vaultAdress, $nonce);
    //     $isTestnet = $this->safe_bool($this->options, 'sandboxMode', false);
    //     $phantomAgent = $this->construct_phantom_agent($hash, $isTestnet);
    //     // $data = array(
    //     //     'domain' => array(
    //     //         'chainId' => 1337,
    //     //         'name' => 'Exchange',
    //     //         'verifyingContract' => '0x0000000000000000000000000000000000000000',
    //     //         'version' => '1',
    //     //     ),
    //     //     'types' => array(
    //     //         'Agent' => array(
    //     //             array( 'name' => 'source', 'type' => 'string' ),
    //     //             array( 'name' => 'connectionId', 'type' => 'bytes32' ),
    //     //         ),
    //     //         'EIP712Domain' => array(
    //     //             array( 'name' => 'name', 'type' => 'string' ),
    //     //             array( 'name' => 'version', 'type' => 'string' ),
    //     //             array( 'name' => 'chainId', 'type' => 'uint256' ),
    //     //             array( 'name' => 'verifyingContract', 'type' => 'address' ),
    //     //         ),
    //     //     ),
    //     //     'primaryType' => 'Agent',
    //     //     'message' => $phantomAgent,
    //     // );
    //     $zeroAddress = $this->safe_string($this->options, 'zeroAddress');
    //     $chainId = 1337; // check this out
    //     $domain = array(
    //         'chainId' => $chainId,
    //         'name' => 'Exchange',
    //         'verifyingContract' => $zeroAddress,
    //         'version' => '1',
    //     );
    //     $messageTypes = array(
    //         'Agent' => array(
    //             array( 'name' => 'source', 'type' => 'string' ),
    //             array( 'name' => 'connectionId', 'type' => 'bytes32' ),
    //         ),
    //     );
    //     $msg = $this->eth_encode_structured_data($domain, $messageTypes, $phantomAgent);
    //     $signature = $this->sign_message($msg, $this->privateKey);
    //     return $signature;
    }

    public function sign_user_signed_action($messageTypes, $message) {
    //     $zeroAddress = $this->safe_string($this->options, 'zeroAddress');
    //     $chainId = 421614; // check this out
    //     $domain = array(
    //         'chainId' => $chainId,
    //         'name' => 'HyperliquidSignTransaction',
    //         'verifyingContract' => $zeroAddress,
    //         'version' => '1',
    //     );
    //     $msg = $this->eth_encode_structured_data($domain, $messageTypes, $message);
    //     $signature = $this->sign_message($msg, $this->privateKey);
    //     return $signature;
    }
}
