<?php

namespace ccxt\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class kuru extends \ccxt\Exchange {
    public function public_get($params = array()) {
        return $this->request('/', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_fetchmarkets($params = array()) {
        return $this->request('fetchMarkets', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_fetchorders($params = array()) {
        return $this->request('fetchOrders', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_fetchorderbook($params = array()) {
        return $this->request('fetchOrderbook', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_fetchorder($params = array()) {
        return $this->request('fetchOrder', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_fetchtrades($params = array()) {
        return $this->request('fetchTrades', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_fetchohlcv($params = array()) {
        return $this->request('fetchOHLCV', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function private_get_fetchopenorders($params = array()) {
        return $this->request('fetchOpenOrders', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function private_get_fetchclosedorders($params = array()) {
        return $this->request('fetchClosedOrders', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function private_get_fetchstatus($params = array()) {
        return $this->request('fetchStatus', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function private_get_fetchmytrades($params = array()) {
        return $this->request('fetchMyTrades', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function private_post_createorder($params = array()) {
        return $this->request('createOrder', 'private', 'POST', $params, null, null, array("cost" => 1));
    }
    public function private_post_cancelorder($params = array()) {
        return $this->request('cancelOrder', 'private', 'POST', $params, null, null, array("cost" => 1));
    }
    public function publicGet($params = array()) {
        return $this->request('/', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetFetchMarkets($params = array()) {
        return $this->request('fetchMarkets', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetFetchOrders($params = array()) {
        return $this->request('fetchOrders', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetFetchOrderbook($params = array()) {
        return $this->request('fetchOrderbook', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetFetchOrder($params = array()) {
        return $this->request('fetchOrder', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetFetchTrades($params = array()) {
        return $this->request('fetchTrades', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetFetchOHLCV($params = array()) {
        return $this->request('fetchOHLCV', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function privateGetFetchOpenOrders($params = array()) {
        return $this->request('fetchOpenOrders', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function privateGetFetchClosedOrders($params = array()) {
        return $this->request('fetchClosedOrders', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function privateGetFetchStatus($params = array()) {
        return $this->request('fetchStatus', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function privateGetFetchMyTrades($params = array()) {
        return $this->request('fetchMyTrades', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function privatePostCreateOrder($params = array()) {
        return $this->request('createOrder', 'private', 'POST', $params, null, null, array("cost" => 1));
    }
    public function privatePostCancelOrder($params = array()) {
        return $this->request('cancelOrder', 'private', 'POST', $params, null, null, array("cost" => 1));
    }
}
